Rétropédalage sur l'utilisation du markdown
OSGeo-fr/QGIS-conf-fr-website pull request #222
Opened 2024-09-23 12:28 UTC by DelazJ

reverts 1d844bb
Apparemment le markdown seul ne rend pas bien sur [notre site](https://conf.qgis.osgeo.fr/z30_mecenat.html). Si quelqu'un sait pourquoi, je veux bien qu'il partage.
En attendant, je revert le formatage...

2024-09-23 13:01 UTC, jmarsac commented
@DelazJ  Apparemment, cela tient au fait que le texte est à l'intérieur de balises HTML. Il n'est donc pas traité par le processeur. Tu observeras que les textes ne sont pas non plus en italiques  dans le rendu. 

Je pense qu'on pourrait simplement supprimer le côté *dépliable* du paragraphe.

2024-09-23 15:12 UTC, DelazJ commented
> Je pense qu'on pourrait simplement supprimer le côté dépliable du paragraphe.

Done!

2024-09-24 09:27 UTC, jmarsac requested changes
Une modif de détail
```diff
- *  ou encore en achetant t-shirt, mug ou autres goodies sur le [shop](https://shop.spreadshirt.net/qgis/)
+ *  ou encore en achetant tee-shirt, mug ou autres goodies sur la boutique](https://shop.spreadshirt.net/qgis/)
```

2024-09-24 21:53 UTC, jmarsac commented
@DelazJ  tu n'es pas d'accord avec *tee-shirt* plutôt que *t-shirt* ?

2024-09-25 05:06 UTC, DelazJ commented
Je l'avais pas vu dans le diff.

2024-09-25 23:03 UTC, jmarsac approved these changes
Merci @DelazJ

2024-09-25 23:03 UTC, merged