ajout partenaires CRAIG et empreinte digitale
OSGeo-fr/QGIS-conf-fr-website pull request #46
Opened 2020-10-22 19:54 UTC by haubourg

Hello, voilà une proposition d'ajout des partenaires CRAIG et empreinte digitale

2020-10-22 21:17 UTC, jmarsac requested changes
Merci @haubourg, je remplaceraisle §

 _Le passage de l'évènement en distanciel nécessite des outils fiables et robustes. Pour autant, l'OSGeo-FR n'oublie pas ses valeurs de promotion du logiciel libre et d'une approche éthique du numérique. Nous avons recherché un partenaire qui porte ces mêmes valeurs que nous pour nous appuyer pour les outils de visio-conférence et diffusion vidéo, hébergés en France évidemment. La SCOP Empreinte digitale nous a proposé son infrastructure et son savoir faire autour des l'informatique libre. Bravo à eux et merci !_ 

par

Le passage de l'évènement en distanciel nécessite des outils fiables et robustes. Pour autant, l'OSGeo-FR n'oublie pas ses valeurs d'approche éthique du numérique et de promotion du logiciel libre.  Pour nous appuyer sur les outils de visio-conférence et diffusion vidéo, nous avons recherché un partenaire qui porte ces mêmes valeurs et utilisent des serveurs localisés en France . La SCOP Empreinte digitale nous a proposé son infrastructure et son savoir faire autour de l'informatique libre. Bravo à eux et merci !

Sinon ok pour moi (peut-être une ou deux fautes à corriger une fois la rédaction finalisée).
Question subsidiaire: je ne sais comment visualiser les branches de développement du site ?

2020-10-23 07:59 UTC, SebastienPeillet commented on z30_parrainages.md
> +_Empreinte Digitale est une entreprise coopérative basée à Angers. Elle développe des solutions numériques sur-mesure à partir de technologies libres et open source._
J'aurai adopté la même disposition pour les deux partenaires à savoir : 

- logo
- présentation
- url

2020-10-23 07:59 UTC, SebastienPeillet commented on z30_parrainages.md
> +Le passage de l'évènement en distanciel nécessite des outils fiables et robustes. Pour autant, l'OSGeo-FR n'oublie pas ses valeurs de promotion du logiciel libre et d'une approche éthique du numériqu
```suggestion
Le passage de l'évènement en distanciel nécessite des outils fiables et robustes. Pour autant, l'OSGeo-FR n'oublie pas ses valeurs de promotion du logiciel libre et d'une approche éthique du numérique. Nous avons recherché un partenaire qui porte ces mêmes valeurs pour nous appuyer pour les outils de visio-conférence et diffusion vidéo, hébergés en France évidemment. La SCOP Empreinte digitale nous a proposé son infrastructure et son savoir faire autour des l'informatique libre. Bravo à eux et merci !
```

ou bien

```suggestion
Le passage de l'évènement en distanciel nécessite des outils fiables et robustes. Pour autant, l'OSGeo-FR n'oublie pas ses valeurs de promotion du logiciel libre et d'une approche éthique du numérique. Nous avons recherché un partenaire qui porte les mêmes valeurs que nous pour nous appuyer pour les outils de visio-conférence et diffusion vidéo, hébergés en France évidemment. La SCOP Empreinte digitale nous a proposé son infrastructure et son savoir faire autour des l'informatique libre. Bravo à eux et merci !
```

2020-10-23 08:03 UTC, SebastienPeillet commented
> Question subsidiaire: je ne sais comment visualiser les branches de développement du site ?

dans ton dépôt local tu peux utiliser : 
```bash
git checkout ajout_partenaires #le nom de la branche
```

ça mettra à jour les fichiers et si tu lances : 
```bash
docker run --rm --volume="$PWD:/srv/jekyll" --volume="$PWD/vendor/bundle:/usr/local/bundle" --env JEKYLL_ENV=development -p 4000:4000 jekyll/jekyll:3.8 jekyll serve
```
le serveur se lance en local à l'adresse 0.0.0.0:4000 .

De la même manière pour revenir sur master : 
```bash
git checkout master
```

2020-10-23 10:51 UTC, jmarsac commented
Merci @SebastienPeillet  pour la commande docker

2020-10-23 12:15 UTC, haubourg commented on z30_parrainages.md
> +_Empreinte Digitale est une entreprise coopérative basée à Angers. Elle développe des solutions numériques sur-mesure à partir de technologies libres et open source._
@SebastienPeillet j'ai poussé un fix

2020-11-05 15:10 UTC, merged