Add sponsors
OSGeo-fr/QGIS-conf-fr-website pull request #48
Opened 2020-11-24 10:27 UTC by GlaDal

_(Pour essayer de faire les choses correctement, je mets une PR ici !_) 
Je ne sais pas trop où ça en est mais si Oslandia et 3Liz ont validé leur soutien à l'évènement il faudrait mettre à jour la page des parrainages du site avec logo et texte si convenu, non ?

2020-11-24 10:42 UTC, haubourg requested changes
@Gladal tu as restauré une branche de l'an dernier, mais ce n'est pas la bonne liste de sponsors pour cette année. Je t'ai fais des commentaires en détail

2020-11-24 10:42 UTC, haubourg commented on z30_parrainages.md
> +[![IDGeo](/images/idgeo.png)](https://www.idgeo.fr)
Je n'ai pas vu passer la proposition IDGEO, j'ai raté quelquechose?

2020-11-24 10:42 UTC, haubourg commented on z30_parrainages.md
> +[![Camptocamp](/images/camptocamp.png)](https://www.camptocamp.com/)
même chose

2020-11-24 10:42 UTC, haubourg commented on z30_parrainages.md
> +[![Surface Libre](/images/surfacelibre.png)](http://www.surfacelibre.fr)
même chose

2020-11-24 10:42 UTC, haubourg commented on z30_parrainages.md
> +[![Azimut](/images/azimut.png)](https://www.azimut.fr)
même chose ( ping @jmarsac je n'ai pas vu passer de proposition)

2020-11-24 10:49 UTC, jmarsac commented on z30_parrainages.md
> +[![IDGeo](/images/idgeo.png)](https://www.idgeo.fr)
Je ne pense pas. Pas vu non plus

2020-11-24 10:50 UTC, jmarsac commented on z30_parrainages.md
> +[![Azimut](/images/azimut.png)](https://www.azimut.fr)
En effet, Azimut sera soutien :)

2020-11-24 10:52 UTC, haubourg commented on z30_parrainages.md
> +[![Azimut](/images/azimut.png)](https://www.azimut.fr)
> En effet, Azimut sera soutien :)

  \o/

2020-11-25 08:54 UTC, haubourg commented
@GlaDal la page de parrainage était complétement en vrac avec des informations fausse, ma faute, tout fait trop vite. J'ai ouvert une nouvelle PR #50 pour mettre ça au carré

@jmarsac @GlaDal je merge quand c'est bon pour vous

2020-11-30 12:44 UTC, GlaDal commented
> 
> 
> @GlaDal tu as restauré une branche de l'an dernier, mais ce n'est pas la bonne liste de sponsors pour cette année. Je t'ai fais des commentaires en détail

@haubourg Oui, désolé, j'maitrise pas encore très bien Github (disons pas du tout pour être honnête !)

2020-11-30 13:33 UTC, haubourg commented
@GlaDal haha, c'est un long chemin tortueux git / gitTruc. Je n'aurais pas la prétention de maitriser correctement non plus. Cette PR est obsolète, je la ferme, la #50 a pris le relais

2020-11-30 13:33 UTC, closed without merging