Add mesh summary
OSGeo-fr/QGIS-conf-fr-website pull request #54
Opened 2020-12-08 20:46 UTC by pblottiere

2020-12-08 20:47 UTC, pblottiere commented
ping @haubourg

2020-12-08 21:46 UTC, SebastienPeillet requested changes
Une petite coquille et une suggestion. Sinon c'est bon pour moi !

2020-12-08 21:46 UTC, SebastienPeillet commented on z20_programme.md
> +La flexibilité spatiale des maillages permet une précision vectorielle en 3 dimensions et une représentation comparable aux rasters avec en plus les champs vectoriels et la temporalité, et cela avec
```suggestion
La flexibilité spatiale des maillages permet une précision vectorielle en 3 dimensions et une représentation comparable aux rasters tout en bénéficiant des champs vectoriels et la temporalité. De plus les maillages permettent également de réaliser une économie de taille des données.
```
C'est une simple suggestion, la phrase était un peu longue à mon goût mais je te laisse arbitrer :)

2020-12-08 21:46 UTC, SebastienPeillet commented on z20_programme.md
> +Les données exploitables peuvent être des données climatiques/météorologiques/atmosphériques, des résultats de modèles hydrodynamiques on encore de Modèle Numérique de Terrain par triangulation.
```suggestion
Les données exploitables peuvent être des données climatiques/météorologiques/atmosphériques, des résultats de modèles hydrodynamiques ou encore de Modèle Numérique de Terrain par triangulation.
```

2020-12-08 21:50 UTC, pblottiere commented on z20_programme.md
> +La flexibilité spatiale des maillages permet une précision vectorielle en 3 dimensions et une représentation comparable aux rasters avec en plus les champs vectoriels et la temporalité, et cela avec
autant pinger l'auteur :)

@vcloarec?

2020-12-08 21:51 UTC, pblottiere commented
Merci pour la review @SebastienPeillet :+1:

2020-12-08 21:55 UTC, SebastienPeillet commented on z20_programme.md
> +La flexibilité spatiale des maillages permet une précision vectorielle en 3 dimensions et une représentation comparable aux rasters avec en plus les champs vectoriels et la temporalité, et cela avec
Haha effectivement !

2020-12-09 00:46 UTC, vcloarec commented on z20_programme.md
> +La flexibilité spatiale des maillages permet une précision vectorielle en 3 dimensions et une représentation comparable aux rasters avec en plus les champs vectoriels et la temporalité, et cela avec
```suggestion
La flexibilité spatiale des maillages permet une précision vectorielle en 3 dimensions et une représentation comparable aux rasters tout en bénéficiant des champs vectoriels, de la temporalité et d'une taille de données réduite.
```

2020-12-09 00:47 UTC, vcloarec commented on z20_programme.md
> +La flexibilité spatiale des maillages permet une précision vectorielle en 3 dimensions et une représentation comparable aux rasters avec en plus les champs vectoriels et la temporalité, et cela avec
merci pour la relecture, je propose cette dernière variante

2020-12-09 08:05 UTC, haubourg commented
C'est bon pour moi! On fusionne (atttention, ici on cause français ;-) )

2020-12-09 08:05 UTC, merged