Ajout du formulaire d'inscription et du détail des ateliers
OSGeo-fr/QGIS-conf-fr-website pull request #62
Opened 2020-12-09 20:28 UTC by haubourg

@SebastienPeillet cette fois j'ai pû tester en local (encore un problème chaise-clavier) 

@jmarsac @DelazJ je laisse ça à vos yeux experts, mais on est bons normalement !

2020-12-09 20:47 UTC, pblottiere commented on z20_programme.md
> +**Animateurs** : Jean-Marie Arsac (Azimuth) / Loïc Bartoletti (Oslandia)
```suggestion
**Animateurs** : Jean-Marie Arsac (Azimut) / Loïc Bartoletti (Oslandia)
```

2020-12-09 20:48 UTC, pblottiere commented on z20_programme.md
> +* Quelle formules pour 2021? Plus de sessions courtes?
```suggestion
* Quelles formules pour 2021? Plus de sessions courtes? 
```

2020-12-09 20:49 UTC, pblottiere commented on z20_programme.md
> +**Animateur** : Régis Haubourg (OSGeo-FR) / Marjorie FANGAIN
```suggestion
**Animateurs** : Régis Haubourg (OSGeo-FR) / Marjorie FANGAIN (Keolis)
```

2020-12-09 20:50 UTC, pblottiere commented on z20_programme.md
> +- apporter sa liste de bug constatés
```suggestion
- apporter sa liste de bugs constatés
```

2020-12-09 20:50 UTC, pblottiere commented on z20_programme.md
> +**Animateurs** : Sébastien Peillet / Harrissou Sant-anna
```suggestion
**Animateurs** : Sébastien Peillet (Oslandia) / Harrissou Sant-anna
```

2020-12-09 20:52 UTC, pblottiere commented on z20_programme.md
> +* Lire les exigences techniques logiciel"	"* L'instance Lizmap sera hébergée chez 3Liz pour les besoins de la formation.
C'est bizarre là, mais je ne sais pas trop ce qui est attendu. À revoir donc.

2020-12-09 22:34 UTC, SebastienPeillet requested changes

2020-12-09 22:34 UTC, SebastienPeillet commented on z20_programme.md
> + <tr class="impair"><td>09:35</td><td><a href="#nouveautés-qgis--partage-de-styles-et-modèles-deModel-mise-en-page-via-le-hub-styles---pierre-serafini---sopreco">Nouveautés QGIS : Partage de styles e
```suggestion
 <tr class="impair"><td>09:35</td><td><a href="#nouveautés-qgis--partage-de-styles-et-modèles-de-mise-en-page-via-le-hub-styles---pierre-serafini---sopreco">Nouveautés QGIS : Partage de styles et modèles de mise en page via le Hub Styles - Pierre Serafini - SOPRECO</a></td><td>7 min.</td></tr>
```

Une petite coquille s'est glissé :) le curseur devait pas être au bon endroit

2020-12-09 22:34 UTC, SebastienPeillet commented on z20_programme.md
> +</a>
```suggestion

```

2020-12-09 22:34 UTC, SebastienPeillet commented on z20_programme.md
> -Dans un contexte global d’augmentation des pressions d’origine naturelle ou humaine, le patrimoine archéologique est de plus en plus menacé. Sa préservation passe par une meilleure connaissance des s
@haubourg C'est une manip volontaire la suppression de ce paragraphe ?

2020-12-09 22:34 UTC, SebastienPeillet commented on z20_programme.md
> +- déclaration et triage de bug
```suggestion
- déclaration et triage de bugs
```

2020-12-09 22:34 UTC, SebastienPeillet commented on z20_programme.md
> +* Mais si vous souhaitez utiliser votre propre instance Lizmap, il existe une machine virtuelle Vagrant et une solution Docker que vous pouvez utiliser sur votre propre ordinateur (même sous Windows)
```suggestion
* Lire les exigences techniques logiciel
* L'instance Lizmap sera hébergée chez 3Liz pour les besoins de la formation.  Mais si vous souhaitez utiliser votre propre instance Lizmap, il existe une machine virtuelle Vagrant et une solution Docker que vous pouvez utiliser sur votre propre ordinateur (même sous Windows), mais son utilisation ne sera pas couverte par l'atelier. Nous vous recommandons l'utilisation de l'instance qui sera mise en place pour les besoins de l'atelier.
```

Je pense que c'est plutôt ça qui est souhaité...

2020-12-09 22:34 UTC, jmarsac commented on z20_programme.md
> +**Animateur** : Régis Haubourg (OSGeo-FR) / Marjorie FANGAIN
**Animateurs** : Marjorie Fangainv(Keolis) / Régis Haubourg (OSGeo-FR)

2020-12-09 22:35 UTC, jmarsac commented on z20_programme.md
> +* Lire les exigences techniques logiciel"	"* L'instance Lizmap sera hébergée chez 3Liz pour les besoins de la formation.
@pblottiere je suis comme toi

2020-12-09 22:37 UTC, jmarsac commented on z20_programme.md
> +**Animateurs** : Sébastien Peillet / Harrissou Sant-anna
Harrissou Sant-anna (Groupe utilisateurs QGIS francophones)
@DelazJ cela te va ou tu préfères mettre ton employeur ?

2020-12-09 22:39 UTC, jmarsac commented on z20_programme.md
> +* Quelle formules pour 2021? Plus de sessions courtes?
* Quelle formule pour 2021 ?
* Plus de sessions courtes ?

2020-12-10 07:14 UTC, DelazJ reviewed
J'envoie sans trop m'être relu et il y a surement des redondances avec d'autres relecteurs (j'avais relu hier et suis allé au lit sans avoir envoyé)

2020-12-10 07:14 UTC, DelazJ commented on z20_programme.md
> +**Animateur** : Sébastien Peillet (Oslandia)
```suggestion
**Animateur** : Sébastien Peillet (Oslandia) / Harrissou Sant-Anna (Groupe Utilisateurs QGIS Francophones)
```
Si @SebastienPeillet en est d'accord.

2020-12-10 08:14 UTC, haubourg commented on z20_programme.md
> +* Lire les exigences techniques logiciel"	"* L'instance Lizmap sera hébergée chez 3Liz pour les besoins de la formation.
@gustry tu pourrais préciser les infos pour l'atelier lizmap ?

2020-12-10 08:17 UTC, haubourg commented on z20_programme.md
> -Dans un contexte global d’augmentation des pressions d’origine naturelle ou humaine, le patrimoine archéologique est de plus en plus menacé. Sa préservation passe par une meilleure connaissance des s
Nope.

2020-12-10 08:20 UTC, haubourg commented on z20_programme.md
> +### Github, comment entrer dans le projet QGIS et participer à la communauté
C'était volontaire à cause des ancres html (je sais pas gérer le `?`)

2020-12-10 08:22 UTC, haubourg commented on z20_programme.md
> +- configuration
Je propose de merger et corriger au fur et à mesure

2020-12-10 08:23 UTC, pblottiere commented on z20_programme.md
> +- configuration
OK pour merger mais faudrait d'abord dé-supprimer le paragraphe supprimé je pense :)

2020-12-10 08:26 UTC, haubourg commented on z20_programme.md
> -Dans un contexte global d’augmentation des pressions d’origine naturelle ou humaine, le patrimoine archéologique est de plus en plus menacé. Sa préservation passe par une meilleure connaissance des s
c'est restauré

2020-12-10 08:27 UTC, haubourg commented on z20_programme.md
> +- configuration
@pblottiere c'est fait

2020-12-10 08:28 UTC, haubourg commented on z20_programme.md
> +* Lire les exigences techniques logiciel"	"* L'instance Lizmap sera hébergée chez 3Liz pour les besoins de la formation.
ça m'a l'air mieux maintenant; je ferme

2020-12-10 08:29 UTC, merged

2020-12-10 08:30 UTC, haubourg commented
Mergé! On finalise sur d'autres PR si besoin

2020-12-10 08:30 UTC, pblottiere commented
Top, merci pour tout le travail @haubourg :+1:

2020-12-10 09:21 UTC, DelazJ commented on z20_programme.md
> +### Github, comment entrer dans le projet QGIS et participer à la communauté
Justement, je serais curieux de connaître les limitations (techniques, graphiques?) qui font qu'on doive se farcir le html à la mano... c'est compliqué et sujet à typo donc broken link. 
Bref, peut-être un chantier "Outils" à envisager pour plus tard...

2020-12-10 09:29 UTC, haubourg commented on z20_programme.md
> +### Github, comment entrer dans le projet QGIS et participer à la communauté
@DelazJ Si tu as des propositions, je suis tout ouïe, mais je ne connais rien en markdown / site statique qui permette ça.